apps/license/urls.py
from django.urls import path

from apps.license.views import index, license_view, license_list, license_edit, license_delete, LicenseAPI

app_name = "license"

urlpatterns = [
    path('', index, name='index'),
    path('nuevo', license_view, name='license_create'),
    path('listar', license_list, name='license_list'),
    path('editar/<int:id_license>/', license_edit, name='license_edit'),
    path('eliminar/<int:id_license>/', license_delete, name='license_delete'),
    path('api', LicenseAPI.as_view(), name='api'),
]

licenses_tool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('license/', include('apps.license.urls')),
]

apps/license/models.py
from django.db import models

class License(models.Model):
	user = models.CharField(max_length=50)
	company_name = models.CharField(max_length=250)
	serial = models.CharField(max_length=50)
	valid_date = models.DateField()

apps/license/forms.py
from django import forms

from apps.license.models import License

class LicenseForm(forms.ModelForm):

	class Meta:
			model = License

			fields = [
				'user',
				'company_name',
				'serial',
				'valid_date',
			]

			labels = {
				'user': 'Usuario',
				'company_name': 'Nombre Empresa',
				'serial': 'Serial',
				'valid_date': 'Fecha Validacion',	
			}

			widgets = {
				'user': forms.TextInput(attrs={'class': 'form-control'}),
				'company_name': forms.TextInput(attrs={'class': 'form-control'}),
				'serial': forms.TextInput(attrs={'class': 'form-control'}),
				'valid_date': forms.TextInput(attrs={'class': 'form-control'}),
			}

apps/license/views.py
import json
from rest_framework.views import APIView

from django.shortcuts import render, redirect
from django.http import HttpResponse

from apps.license.forms import LicenseForm
from apps.license.models import License
from apps.license.serializers import LicenseSerializer

def index(request):
	return render(request, 'license/index.html')

def license_view(request):
	if request.method == 'POST':
		form = LicenseForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('license:index')
	else:
		form = LicenseForm()
 
	return render(request, 'license/license_form.html', {'form':form})

def license_list(request):
	license = License.objects.all().order_by('id')
	contexto = {'licenses': license}
	return render(request, 'license/license_list.html', contexto)

def license_edit(request, id_license):
	license = License.objects.get(id=id_license)
	if request.method == 'GET':
		form = LicenseForm(instance=license)
	else:
		form = LicenseForm(request.POST, instance=license)
		if form.is_valid():
			form.save()
		return redirect('license:license_list')
	return render(request, 'license/license_form.html', {'form': form})

def license_delete(request, id_license):
	license = License.objects.get(id=id_license)
	if request.method == 'POST':
		license.delete()
		return redirect('license:license_list')
	return render(request, 'license/license_delete.html', {'license': license})


class LicenseAPI(APIView):
	serializer = LicenseSerializer

	def get(self, request, format=None):
		list_licenses = License.objects.all()
		response = self.serializer(list_licenses, many=True)

		return HttpResponse(json.dumps(response.data), content_type='application/json')

templates/base/base.html
{% load staticfiles  %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block extrahead %}
	{% endblock %}
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document{% endblock %}</title>
</head>
<body>
	{% block header %}
		<h4>Este es el Header base</h4>
	{% endblock %}

	{% block content %}
		<h5>Contenido del archivo base</h5>
	{% endblock %}

	{% block footer %}
		<h5>Footer del archivo base</h5>
	{% endblock %}

	<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <script scr="{% static 'js/bootstrap.min.js' %}"></script>

  {% block extrajs %}
	{% endblock %}
</body>
</html>

templates/license/index.html
{% extends 'base/base.html' %}

{% block title %}
	App Licenses
{% endblock %}

{% block header %}
	<h5>Este es el header del index de la app license</h5>
{% endblock %}

{% block content %}
	<h5>Soy el contenido de app license</h5>
{% endblock %}

templates/license/license_delete.html
{% extends 'base/base.html' %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		<h3>Desea eliminar el registro de {{ license.company_name }}?</h3>
		<button class="btn btn-danger" type="submit">Eliminar</button>
		<a class="btn btn-default" href="{% url 'license:license_list' %}">Cancelar</a>
	</form>
{% endblock %}

templates/license/license_form.html
{% extends 'base/base.html' %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Guardar</button>
	</form>
{% endblock %}

templates/license/license_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Usuario</td>
			<td>Empresa</td>
			<td>Serial</td>
			<td>Fecha Validacion</td>
			<td>Acciones</td>
		</tr>
	</thead>

	<tbody>
		{% if licenses %}
		{% for license in licenses %}
		<tr>
			<td>{{ license.id }}</td>
			<td>{{ license.user }}</td>
			<td>{{ license.company_name }}</td>
			<td>{{ license.serial }}</td>
			<td>{{ license.valid_date }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'license:license_edit' license.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'license:license_delete' license.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% else %}
		<h1>No hay registro de licencias</h1>
		{% endif %}
	</tbody>
</table>

{% endblock %}